alfheim: ENC[AES256_GCM,data:0IGnojKYDIxpimLl6JzSjss5Gk3ZwYRfvWE4Cg1qQuCI1B06E1J1LmXClLBzYkyKCgA9sk5aEfCRPDXsyNoEFyJ+ItYa42oh8/Sk4Y9DL6+sC6BCTBaxsL8VxD6+L4x4xyQdWydofz3CiFti+JxktyT9QP8ZjJfxmApBwJa9s/79JNdeJXEDSFH+J1mSTtFZokqv7ou2lmjm0MWQoWQaaR0/Ia0SGW2f+hZ3l+OxfF0DuRLo6s+00A==,iv:JOXnmCCcsqgPnUiU1Vpuw3K6bRYxAHWKpZnNXTLSMCc=,tag:Sm5szNdXO0fbQ6Y3X+w55Q==,type:str]
mimisbrunnr: ENC[AES256_GCM,data:oo7C9Ze1b0B5IJ+KvMBLGoMIM0VPSePdMYOuUaWTxB6sfTy7CCWEeNTH65wp3DV1srNdy22eCqHW7fbQfW4ItV/Fagkkd14YxowlUDsd6rpiZlxSjQa312Iem4N4mQxSImDygeAhHIWbzPTKKygLplhSuFfQyesWX9kPryTuVcQqJb73dGBOLUKka2Li1bVuG5XOegsZwREYDZrEZe+ECImNYD6wOpgyYtz9+ruiWF0H7nmo6MihrA==,iv:ZotVhgoasFH/7FQ3C5P3jqC7w6etw3p7gZGVoNRC2rw=,tag:S0H4tSNTyyQ4ESyxGr7WLQ==,type:str]
nidavellir: ENC[AES256_GCM,data:1/EbZF2KTH/3aGNtOiMtVuff5ee+rvSKmJWHvjjJU3QgxPqgnPq+xFLHpbNhH8mC7WrUPAIt+H4D310PfheiJMl5G83ZtLPdQUu3L6XyVcojenWt8qdXZCH1EAhbJmQFKrT+52WSXtDNe0WmNNsWQYRy2lsKLnWcwE6WGv9O3UsmVyAA1ld7ZKqJO1BbTmVll/LF2JB18PJ8mw+/vZCn30aZIWQOzjBRGr12aiF0CJWZ5OHmGcYQkw==,iv:/t3h85owQb5JXfydC8O+7kjzMD24zI/7OAvhhIiyVTE=,tag:sAa+194D66gk1QI2PcnYyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN1JPdURTTlh6YWZKd3Jx
            K2xWQlA5TzRXbjlaOTJqMmE1K2Z3MGZFTFJJCnBoRjhyakZ3ZUJselBPeGNSNzV3
            YmlOYkNkNVo3dTdTUUxxeTRPcFZoN00KLS0tIFZ5WUJwQ0dmclp1c0gxT2lTeDhY
            WFRHZndBaTFxZ2MyNnhUQ2wzNUJWY2cK1QPfWmcgSDonzsLMfBt4TlJb3J+wZw7R
            PO6wSlOovvJNXEg0T4/cY7D7TgqF5DPbL+LtyUeHWLDFtZQ1+Ny6/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l4h8jrc6yltllsq293tczg3shqps04zuw8u4w32nek7kdh95g98s4q3ykt
    lastmodified: "2026-10-09T14:24:35Z"
    mac: ENC[AES256_GCM,data:6ahF/ywSSFQwoDCKeS68nn+mk0tvNLW8mjjnGOZT5yRIuYBL+qEa70Dyv/sEJuTkGN2tdyEkPsqKUhJNl/ZcHueyg8AhyyCvRvfgMHFctYgVFNNUHD+wJ4GHUTY9tW+ka+L1rs2XioRc9ye5Md/P6D5BI3Of80DHoVf3zYhuYUc=,iv:KXBwiXpVAcnlhAg1Erilg+4f5JzgBVNavmhvZHaFjO4=,tag:7fhx2XIgSghk2sXegmG9IA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
